apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: home-wolfs-io
spec:
  secretName: home-wolfs-io-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging
  dnsNames:
  - '*.home.wolfs.io'
