---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: core
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./clusters/republiccity/core
  prune: true
  sourceRef:
    kind: GitRepository
    name: cabbagecorp
