apiVersion: v1
kind: Secret
metadata:
    name: traefik-forward-auth-secrets
type: Opaque
stringData:
    google-client-id: ENC[AES256_GCM,data:a3/qhppZJdmaZor2l/jKtI7aY23EFgEXOXbXpk/JE60+1MVtHlCyR8L17d+RgeB+8WeN/MuCEhmDlhexYnmz9yv8qjUsKcX5,iv:6H5yat7HSO8xKJ4mfbk7gXQLD5BTsTJnTN69Af/25lQ=,tag:khK4X1/R1JFQSJ2DfeVGBg==,type:str]
    google-client-secret: ENC[AES256_GCM,data:lMdh9pQlw6MbNzmGPHs7eJk2eNvdqjVX,iv:3fsNTD0+xArMCBL7cR52ByTspAOZwOVs18jJdieVIb8=,tag:eRpRiIyZcv696Fyqbvzr0w==,type:str]
    secret: ENC[AES256_GCM,data:ASLzIkjEbbKZ7K1YsUPsCyMkY44=,iv:TlyEeWVDYse9ZXWLCFb+6MJGmVzFRhY/O4ear3uo844=,tag:ywUoKHQ27a2OQ9GAPZDr1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-06-28T16:09:13Z'
    mac: ENC[AES256_GCM,data:LYBkKRCWBla3jwSbAPigZNsnae9G7RnFnC0oRrbVh354WOzS+j6YkpUpnM3t0OSH+Zpvq+iV4JJZ+1VhJ4n+gGvMS2dOUbHwTTbGwpWE8IxC874E44XDMbP/k07GJh4qW++Oi+KD0p91/p4JWhF2jQo69e6GeEqcnlIO6wpSabI=,iv:KnbFtg1pu33GNQNCMETfMMSDkoazw4HdwDmr8VcjKDM=,tag:9paI5FqDg9Y+6DkJz9UGrA==,type:str]
    pgp:
    -   created_at: '2021-06-28T16:09:12Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwWTm8o+mcOPAQ/9H0D3RPT8DzN1duh0VquM4pchTNNatKzqhL4bXDlkMMsi
            P5JV4Iqw5Y5fgA0qpK+pOdxK+LLVeIj6FgkVrwxuZeCQclhnHt6dl1Wo/AF5a+aq
            HG6Lw1BP8LBMLwvOtwnSx0nOwbctkV0EtM75cLkTTqgi8SdBoS+7FnO+32u18BUE
            7Hb8Rf4VMxYKKqOCOF7QG6kOunTiml8MEDQXjwlw9wQCwufr5KldMVaoHmrB9sZc
            bIL0MZLIHGizxEUnlRgWyRnynaV/hmMyLXcEIV5YK1KKsJYdfacd09zvS/E7gdfb
            bAdPoiL3vpKphmYkjfsKUwUuwmPJDKENElH3LSTebCt5pPavrWygfZmC5IhW4AoQ
            iY+Y+4gT5ETJMr2ExsKEg7bt9r9Pkt7FzFnY8Y5rNxHwr3X22d1QEkbc1caykVR2
            r5SYU0FJTF9FynPwugmisVv8w8hZFWWdk6FUQZexH/fLYqoLl+I4rZK9ZFH9usFR
            JNhiqIcfkStzaEOnpV+dA4LfOlLM00NGFapLBjhq4MFMwNjWyYKa5BSpbdBT7wlH
            7TOP2FmzaAuyGRk2SB5WEsivHyuYlxIrg5ax5tu5qYrED4hQtDLyHKEPvr7Ksu/a
            iVpmbgkABPeqORz9oSLHoielVtdGlQqsFmHZ8JR3tPGX9/KT1VEk3Az8lqTl+ZnS
            XgEBrZTm9kG+0tN1Po3yZfpNiGc4av0kxSKoLiYS5MoJYIW7tTRIlxnH1SngnbeU
            xypADvtmrk9svctY3qEqulZkUOM3Qgx7fNnb0sLLEKAmOj1LF6lyPgkRJVKz7z4=
            =z9LU
            -----END PGP MESSAGE-----
        fp: 70AA61670B7B6E24082AFE161766F2F52885306D
    -   created_at: '2021-06-28T16:09:12Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3O/Hgu1n9uEAQ//cUhBSMqR5izAXjDtDNdTSaldvLyQ2Vy/ccIkU7grvX8/
            CO4/3nD3mHry0rQZdzMF3HqNgNCf9tcG0MbLlE4OfjARpE2skV1d1m5bfCuImV53
            vylNeC2Zht7IeorLSj1NIUTaQ6H87CMr+038k2seewhymQup2JgffkGQVur4gkvA
            iY1s1xw6Uuy6C//T5LZuQTFVZZSl5gr+zNuuVIbTEW3/Vfe3G63VzQHX9ve0GWo6
            cl4xa1aLmEKElNYJdLUG2RT97mPRpwPIo/GDGkXKJv6mGFDaWL+oZHikBtc8vGB/
            b3s/fEwcFFBtLnTK7klow2JimdyHWkZ8eYG6iKLAPOOj/9+kx5JhSanbTo6JW0fT
            tSRrxPWFwolMN0b+/4ix6CUIdkfg29RNR/mqCVwoN7SHbmmPwDSN9iXrj8ogPVlf
            HUyG5SUD6hmjVeQh+h4l1BE3G0PzwksrG9bxH8h0h48SOJySGPgXAJE7v2u5cPvz
            ff3BHxFq+wqDKxUARJBd5GoDEGX6W3paVIJTsGU58WWTdfXI0/HW5WrALvjR7+q8
            +0VmCrUAu33+CKLEI+nDkQvkLye7l+Lmi6OLz5dHE+hkQE77G+CtpXcvtB710sm/
            7IILs/OC46BqQuo8Qf2qBSS2ETWABFK+/c7e2YEKARcyeVr3nRvNEMt8EieUWOnS
            XgHdmYGYiqVINH948xbJB+TpZ7nOD3XjTIH8qZL64WGHOl23Sv1slTifKgDIns69
            uiBKe2HSwISrce3MWMzygZDdR08f6ZVUPO4h7ZZPvLG4sPPLm0rqkXMciFgZVz4=
            =OJGF
            -----END PGP MESSAGE-----
        fp: 581CF216C56DE3E37B2A849DCBC7AEF8D170B40C
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
