---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: adguard
  namespace: flux-system
spec:
  chart:
    spec:
      chart: adguard-home
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
  values:
    env:
      TZ: "America/Denver"
    service:
      dns-tcp:
        enabled: true
        type: LoadBalancer
      dns-udp:
        enabled: true
        type: LoadBalancer
